[phases.setup]
apt_packages = ["ffmpeg"]

[start]
# Explicitly add common ffmpeg installation paths to the PATH
# This helps ensure discord.py can find the ffmpeg executable
cmd = "PATH=$PATH:/usr/bin:/usr/local/bin python bot.py"
